In [17]:
import pandas as pd

## #1

In [13]:
# Se exporto el archivo csv
df_aire = pd.read_csv("calidad_aire_estaciones.csv")

df_aire

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
0,EST-6001,Centro Histórico,12.5,28.5,29.1,60,13.9,Verde
1,EST-6002,Zona Industrial,48.0,28.5,24.0,86,10.2,Amarilla
2,EST-6003,Corredor Vial,12.5,NaN,14.6,51,33.5,Naranja
3,EST-6004,Corredor Vial,65.0,18.0,23.1,56,24.4,Verde
4,EST-6005,Centro Histórico,48.0,NaN,20.0,77,8.5,Amarilla
...,...,...,...,...,...,...,...,...
1007,EST-6108,Zona Industrial,22.0,18.0,24.1,40,17.4,Naranja
1008,EST-6109,Zona Industrial,48.0,18.0,16.2,48,16.9,Verde
1009,EST-6110,Parque Natural,22.0,18.0,20.4,60,22.9,Verde
1010,EST-6111,Centro Histórico,12.5,42.0,17.6,72,24.4,Verde
1011,EST-6112,Corredor Vial,12.5,28.5,29.5,94,24.3,Naranja

## #2

In [14]:
#Se extrajo la columna Material_Particulado_PM25
pm25 = df_aire["Material_Particulado_PM25"]

pm25

0       12.5
1       48.0
2       12.5
3       65.0
4       48.0
        ...
1007    22.0
1008    48.0
1009    22.0
1010    12.5
1011    12.5
Name: Material_Particulado_PM25, Length: 1012, dtype: float64

## #3

In [ ]:
# Se extrajo las siguientes columnas que nos piden 
tabla_sel = df_aire[["Sector","Temperatura_C","Alerta_Ambiental"]]

tabla_sel

                Sector  Temperatura_C Alerta_Ambiental
0     Centro Histórico           29.1            Verde
1      Zona Industrial           24.0         Amarilla
2        Corredor Vial           14.6          Naranja
3        Corredor Vial           23.1            Verde
4     Centro Histórico           20.0         Amarilla
...                ...            ...              ...
1007   Zona Industrial           24.1          Naranja
1008   Zona Industrial           16.2            Verde
1009    Parque Natural           20.4            Verde
1010  Centro Histórico           17.6            Verde
1011     Corredor Vial           29.5          Naranja

[1012 rows x 3 columns]

## #4

In [18]:
#busca por etiqueta del índice
df_aire.loc[[175]]

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
175,EST-6176,Zona Industrial,48.0,42.0,28.9,40,16.3,Verde

## #5

In [19]:
# Identificar duplicados
print("Duplicados:", df_aire.duplicated().sum())

df_aire[df_aire.duplicated()]

Duplicados: 12

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
1000,EST-6101,Zona Residencial,35.5,42.0,24.7,74,30.8,Amarilla
1001,EST-6102,Zona Industrial,12.5,18.0,28.4,87,33.8,Verde
1002,EST-6103,Centro Histórico,12.5,18.0,27.1,90,20.5,Amarilla
1003,EST-6104,Corredor Vial,12.5,28.5,14.9,42,20.8,Amarilla
1004,EST-6105,Zona Residencial,48.0,42.0,16.9,71,9.6,Verde
1005,EST-6106,Zona Residencial,22.0,28.5,16.8,89,21.4,Verde
1006,EST-6107,Centro Histórico,35.5,18.0,25.6,94,31.5,Verde
1007,EST-6108,Zona Industrial,22.0,18.0,24.1,40,17.4,Naranja
1008,EST-6109,Zona Industrial,48.0,18.0,16.2,48,16.9,Verde
1009,EST-6110,Parque Natural,22.0,18.0,20.4,60,22.9,Verde
1010,EST-6111,Centro Histórico,12.5,42.0,17.6,72,24.4,Verde
1011,EST-6112,Corredor Vial,12.5,28.5,29.5,94,24.3,Naranja

In [20]:
# Eliminar todos los registros duplicados
df_sin_duplicados = df_aire.drop_duplicates()
df_sin_duplicados

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
0,EST-6001,Centro Histórico,12.5,28.5,29.1,60,13.9,Verde
1,EST-6002,Zona Industrial,48.0,28.5,24.0,86,10.2,Amarilla
2,EST-6003,Corredor Vial,12.5,NaN,14.6,51,33.5,Naranja
3,EST-6004,Corredor Vial,65.0,18.0,23.1,56,24.4,Verde
4,EST-6005,Centro Histórico,48.0,NaN,20.0,77,8.5,Amarilla
...,...,...,...,...,...,...,...,...
995,EST-6996,Zona Residencial,22.0,55.5,31.7,52,14.6,Verde
996,EST-6997,Zona Industrial,35.5,NaN,23.7,49,27.8,Verde
997,EST-6998,Parque Natural,12.5,28.5,18.1,87,11.5,Verde
998,EST-6999,Zona Industrial,22.0,42.0,16.5,71,28.2,Verde
999,EST-7000,Zona Residencial,35.5,55.5,13.3,55,30.3,Amarilla

## #6

In [21]:
#  filtro booleano simple para mostrar únicamente aquellas lecturas donde el Material_Particulado_PM25 supere los 55.0 $\mu g/m^3$.

mascara = df_aire["Material_Particulado_PM25"] > 55.0
pm25_critico = df_aire[mascara]
pm25_critico

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
3,EST-6004,Corredor Vial,65.0,18.0,23.1,56,24.4,Verde
5,EST-6006,Centro Histórico,65.0,NaN,29.7,44,34.1,Naranja
19,EST-6020,Zona Residencial,85.5,42.0,23.2,70,16.6,Naranja
20,EST-6021,Parque Natural,65.0,28.5,24.5,48,15.0,Verde
23,EST-6024,Zona Residencial,110.0,55.5,31.0,78,5.5,Amarilla
...,...,...,...,...,...,...,...,...
987,EST-6988,Parque Natural,85.5,28.5,18.9,51,2.5,Verde
989,EST-6990,Zona Residencial,65.0,28.5,16.4,47,24.6,Verde
990,EST-6991,Parque Natural,65.0,42.0,25.0,45,21.0,Amarilla
992,EST-6993,Zona Residencial,85.5,70.0,19.4,77,14.0,Verde
993,EST-6994,Zona Industrial,65.0,42.0,28.8,79,16.0,Naranja

## #7

In [22]:
# Filtro con .isin(): solo Zona Industrial y Corredor Via
df_aire[df_aire["Sector"].isin(["Zona Industrial", "Corredor Vial"])]

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
1,EST-6002,Zona Industrial,48.0,28.5,24.0,86,10.2,Amarilla
2,EST-6003,Corredor Vial,12.5,NaN,14.6,51,33.5,Naranja
3,EST-6004,Corredor Vial,65.0,18.0,23.1,56,24.4,Verde
6,EST-6007,Corredor Vial,35.5,42.0,31.2,66,29.2,Naranja
9,EST-6010,Corredor Vial,12.5,55.5,20.0,70,13.0,Naranja
...,...,...,...,...,...,...,...,...
1001,EST-6102,Zona Industrial,12.5,18.0,28.4,87,33.8,Verde
1003,EST-6104,Corredor Vial,12.5,28.5,14.9,42,20.8,Amarilla
1007,EST-6108,Zona Industrial,22.0,18.0,24.1,40,17.4,Naranja
1008,EST-6109,Zona Industrial,48.0,18.0,16.2,48,16.9,Verde
1011,EST-6112,Corredor Vial,12.5,28.5,29.5,94,24.3,Naranja

## #8

In [23]:
# Filtro con .between(): humedad entre 60 y 80 inclusive
df_aire[df_aire["Humedad_Relativa"].between(60, 80)]

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
0,EST-6001,Centro Histórico,12.5,28.5,29.1,60,13.9,Verde
4,EST-6005,Centro Histórico,48.0,NaN,20.0,77,8.5,Amarilla
6,EST-6007,Corredor Vial,35.5,42.0,31.2,66,29.2,Naranja
7,EST-6008,Parque Natural,48.0,28.5,20.6,72,29.4,Roja
9,EST-6010,Corredor Vial,12.5,55.5,20.0,70,13.0,Naranja
...,...,...,...,...,...,...,...,...
998,EST-6999,Zona Industrial,22.0,42.0,16.5,71,28.2,Verde
1000,EST-6101,Zona Residencial,35.5,42.0,24.7,74,30.8,Amarilla
1004,EST-6105,Zona Residencial,48.0,42.0,16.9,71,9.6,Verde
1009,EST-6110,Parque Natural,22.0,18.0,20.4,60,22.9,Verde
1010,EST-6111,Centro Histórico,12.5,42.0,17.6,72,24.4,Verde

## #9

In [24]:
# Consulta con .query(): alerta Roja y viento menor a 10.0 km/h
df_aire.query("Alerta_Ambiental == 'Roja' and Velocidad_Viento_kmh < 10.0")

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
232,EST-6233,Corredor Vial,35.5,28.5,26.1,87,2.3,Roja
428,EST-6429,Zona Residencial,12.5,42.0,27.4,74,1.9,Roja
458,EST-6459,Zona Residencial,85.5,70.0,20.1,66,9.2,Roja
482,EST-6483,Corredor Vial,85.5,28.5,27.4,49,5.2,Roja
532,EST-6533,Zona Residencial,48.0,28.5,25.9,41,7.3,Roja
629,EST-6630,Zona Residencial,12.5,NaN,21.9,90,6.8,Roja
670,EST-6671,Parque Natural,12.5,55.5,25.4,67,9.0,Roja
723,EST-6724,Zona Industrial,NaN,28.5,16.7,70,5.3,Roja
804,EST-6805,Centro Histórico,48.0,18.0,14.0,75,6.6,Roja
826,EST-6827,Corredor Vial,12.5,28.5,20.2,53,8.3,Roja
827,EST-6828,Zona Residencial,35.5,28.5,31.8,79,9.6,Roja
887,EST-6888,Parque Natural,NaN,18.0,13.9,84,9.7,Roja
910,EST-6911,Zona Industrial,12.5,55.5,31.2,66,8.3,Roja
994,EST-6995,Centro Histórico,48.0,42.0,26.2,70,8.9,Roja

## #10

In [25]:
# Condición compuesta: sector que inicia con "Zona" y ozono mayor a 40.0
condicion = df_aire["Sector"].str.startswith("Zona") & (df_aire["Nivel_Ozono_ppb"] > 40.0)
df_aire[condicion]

,ID_Estacion,Sector,Material_Particulado_PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Velocidad_Viento_kmh,Alerta_Ambiental
10,EST-6011,Zona Residencial,35.5,95.0,23.1,72,11.7,Verde
19,EST-6020,Zona Residencial,85.5,42.0,23.2,70,16.6,Naranja
22,EST-6023,Zona Residencial,12.5,42.0,27.1,57,16.9,Naranja
23,EST-6024,Zona Residencial,110.0,55.5,31.0,78,5.5,Amarilla
31,EST-6032,Zona Industrial,48.0,42.0,13.8,88,28.7,Verde
...,...,...,...,...,...,...,...,...
995,EST-6996,Zona Residencial,22.0,55.5,31.7,52,14.6,Verde
998,EST-6999,Zona Industrial,22.0,42.0,16.5,71,28.2,Verde
999,EST-7000,Zona Residencial,35.5,55.5,13.3,55,30.3,Amarilla
1000,EST-6101,Zona Residencial,35.5,42.0,24.7,74,30.8,Amarilla
1004,EST-6105,Zona Residencial,48.0,42.0,16.9,71,9.6,Verde

## #11

In [26]:
# Nulos antes de imputar
print(df_aire[["Material_Particulado_PM25", "Nivel_Ozono_ppb"]].isna().sum())

# PM2.5: reemplazar NaN por la media de la columna
media_pm25 = df_aire["Material_Particulado_PM25"].mean()
df_aire["Material_Particulado_PM25"] = df_aire["Material_Particulado_PM25"].fillna(media_pm25)

# Ozono: reemplazar NaN por la constante 0.0
df_aire["Nivel_Ozono_ppb"] = df_aire["Nivel_Ozono_ppb"].fillna(0.0)

# Nulos después de imputar 
print(df_aire[["Material_Particulado_PM25", "Nivel_Ozono_ppb"]].isna().sum())

Material_Particulado_PM25    71
Nivel_Ozono_ppb              71
dtype: int64
Material_Particulado_PM25    0
Nivel_Ozono_ppb              0
dtype: int64

## #12

In [27]:
# Función que clasifica la temperatura
def clasificar_clima(temp):
    if temp < 18:
        return "Frío"
    elif temp <= 25:
        return "Templado"
    else:
        return "Cálido"

# Aplicarla con .apply() para crear la columna Clima
df_aire["Clima"] = df_aire["Temperatura_C"].apply(clasificar_clima)
df_aire[["Temperatura_C", "Clima"]].head()

   Temperatura_C     Clima
0           29.1    Cálido
1           24.0  Templado
2           14.6      Frío
3           23.1  Templado
4           20.0  Templado

## #13

In [29]:
# Renombrar columnas
df_aire = df_aire.rename(columns={
    "Material_Particulado_PM25": "PM25",
    "Velocidad_Viento_kmh": "Viento_KMH"
})

# Reordenar: ID_Estacion y Clima primero
df_aire = df_aire[["ID_Estacion", "Clima", "Sector", "PM25", "Nivel_Ozono_ppb",
                    "Temperatura_C", "Humedad_Relativa", "Viento_KMH", "Alerta_Ambiental"]]

df_aire.head()

,ID_Estacion,Clima,Sector,PM25,Nivel_Ozono_ppb,Temperatura_C,Humedad_Relativa,Viento_KMH,Alerta_Ambiental
0,EST-6001,Cálido,Centro Histórico,12.5,28.5,29.1,60,13.9,Verde
1,EST-6002,Templado,Zona Industrial,48.0,28.5,24.0,86,10.2,Amarilla
2,EST-6003,Frío,Corredor Vial,12.5,0.0,14.6,51,33.5,Naranja
3,EST-6004,Templado,Corredor Vial,65.0,18.0,23.1,56,24.4,Verde
4,EST-6005,Templado,Centro Histórico,48.0,0.0,20.0,77,8.5,Amarilla

## #14

In [30]:
# Agrupar por Sector: promedio de PM25 y máximo de Temperatura_C
df_aire.groupby("Sector").agg({"PM25": "mean", "Temperatura_C": "max"})

                       PM25  Temperatura_C
Sector
Centro Histórico  35.503470           31.5
Corredor Vial     37.085469           31.9
Parque Natural    36.825785           31.9
Zona Industrial   34.610382           31.8
Zona Residencial  36.566566           32.0

## #15

In [31]:
# Función personalizada: rango = máximo - mínimo
def rango(series):
    return series.max() - series.min()

# Aplicarla con .agg() agrupando por Alerta_Ambiental
df_aire.groupby("Alerta_Ambiental")[["PM25", "Humedad_Relativa"]].agg(rango)

                  PM25  Humedad_Relativa
Alerta_Ambiental
Amarilla          97.5                54
Naranja           97.5                55
Roja              97.5                55
Verde             97.5                55

## #16

In [32]:
# Agrupación multinivel: Sector y Alerta_Ambiental
df_aire.groupby(["Sector", "Alerta_Ambiental"]).agg(
    PM25_promedio=("PM25", "mean"),
    Humedad_promedio=("Humedad_Relativa", "mean")
)

                                   PM25_promedio  Humedad_promedio
Sector           Alerta_Ambiental
Centro Histórico Amarilla              36.565514         66.945946
                 Naranja               39.875000         72.541667
                 Roja                  30.837455         58.727273
                 Verde                 34.754388         67.080645
Corredor Vial    Amarilla              40.213031         65.651515
                 Naranja               31.860600         71.200000
                 Roja                  43.934334         67.583333
                 Verde                 36.416471         68.336134
Parque Natural   Amarilla              39.429883         69.705882
                 Naranja               37.061407         69.972973
                 Roja                  35.113177         64.117647
                 Verde                 35.784926         69.333333
Zona Industrial  Amarilla              28.395488         68.000000
                 Naranja               34.039556         68.277778
                 Roja                  38.651501         62.750000
                 Verde                 36.749476         67.252427
Zona Residencial Amarilla              36.161392         70.565217
                 Naranja               40.238515         70.828571
                 Roja                  39.047467         76.000000
                 Verde                 35.124471         67.656863